# Generated by Django 3.1 on 2020-12-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.IntegerField(default=None),
        ),
    ]
