# Generated by Django 3.1 on 2020-12-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_tasklist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='end_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='start_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
