# Generated by Django 3.1 on 2020-12-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20201228_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
