# Generated by Django 3.1 on 2020-12-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_tasklist_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
